### ISSUE TITLE
Workflow - déploiement automatique

### ISSUE THREAD

**Issue by n3rada** [n3rada/ScribUTT#14]
Il serait bénéfique de mettre en place un workflow qui effectue un déploiement automatique à chaque nouvelle Pull Request ou à chaque push, garantissant ainsi la mise à jour constante du dossier "deploy".

Alternativement, reconsidérer entièrement notre approche du déploiement pourrait être une option, en visant à rendre disponible un fichier zip directement dans la section "packages".

Toute personne souhaitant prendre en charge ce projet est la bienvenue ; la voie est libre et la route n'est pas si longue.

**Comment by Zalk0** [comment]
Une solution simple pourrait être tout simplement de générer un artefact avec le workflow et donner le lien du dernier artefact généré grâce à https://nightly.link/

**Comment by n3rada** [comment]
Merci pour ta suggestion @Zalk0 , c'est une idée à considérer d'utiliser [nightly.link](https://nightly.link/) pour simplifier le processus.

Malheureusement, en ce moment, je ne veux pas consacrer du temps pour ce projet. Si quelqu'un d'autre est motivé à implémenter cette solution, je l'encourage vivement à le faire !

Toute contribution serait grandement appréciée.

**Comment by Zalk0** [comment]
Du coup j'ai automatisé le zip en artifact d'action, par contre je ne sais pas du comment fonctionne la section packages.  
Deuxième point, je ne sais pas si c'est pertinent de compiler le pdf dans l'action que j'ai proposée, je l'ai mis dans un autre zip parce que je ne trouvais pas approprié de le mettre dans le deploy que tu veux garder le plus léger possible j'imagine.  
Si quelqu'un a une idée pour le pdf, peut-être créer une autre issue plus adaptée.  
Je te laisse gérer @n3rada

**Comment by n3rada** [comment]
Je pense que tu peux supprimer la génération du pdf. De base c'est inutile, ce qui intéresse les gens c'est de pouvoir importer le `.zip` dans leur outil préféré ! Merci beaucoup.

**Comment by n3rada** [comment]
@Zalk0 pourrais-tu tester que le workflow fonctionne correctement ? Le zip est utilisable et généré où ?

**Comment by Zalk0** [comment]
J'ai rajouté dans le README le lien nightly.link, sinon il suffit d'aller dans l'onglet actions sur github, de cliquer sur la dernière run de l'action deploy et tu devrais voir un artifact.
![image](https://github.com/n3rada/ScribUTT/assets/88582103/a4e81231-0d22-471d-b36b-5fd86a0d3644)

**Comment by Zalk0** [comment]
bump @n3rada

**Comment by n3rada** [comment]
Je n'ai pas le temps de maintenir manuellement ce genre d'actions

**Comment by n3rada** [comment]
Je n'ai pas envie d'allouer du temps pour maintenir manuellement ce genre d'actions, il faudrait trouver une fonctionnalité automatique ou laisser les gens ziper comme des grands !

**Comment by Zalk0** [comment]
Justement il n'y a rien à faire, tu commit ça crée le zip tout seul. Et tu peux cliquer sur le lien dans le Readme pour le télécharger.

**Comment by n3rada** [comment]
Oui voilà, je laisse les gens le prendre ici je veux dire !
