### ISSUE TITLE
La page de garde ne s'affiche pas sur overleaf.com

### ISSUE THREAD

**Issue by ThomasRitaine** [n3rada/ScribUTT#2]
Salut @n3rada !

Déjà, joli projet, bravo ;)

### Contexte
Le site [Overleaf](https://www.overleaf.com) permet d'éditer du LaTeX en ligne.
On peut démarrer un projet à partir [du ZIP que tu fournis](https://github.com/n3rada/ScribUTT/blob/main/deploy/latex-rapport-UTT.zip).

### Problème
Quand on démarre un projet avec ton template, la page de garde ne s'affiche pas.
La page par défaut est `\frontpageST`, mais ce problème est aussi rencontré avec la page de garde de rapport d'UE `\frontpagereports`.

Voici une capture d'écran du problème :

<img width="774" alt="no_page_garde" src="https://user-images.githubusercontent.com/43563793/121357201-e0fa1b80-c931-11eb-9e7a-dfa3ed3ebdd8.PNG">

**Comment by n3rada** [comment]
Salut @ThomasRitaine !

J'avoue n'avoir fait le projet qu'uniquement sur VsCode. 
Je viens de me faire un compte Overleaf, et c'est vrai que c'est super étrange, il n'importe pas la page de garde...

Je vais essayé de comprendre pourquoi, mais qu'une petite demi-heure, après j'ai des projets à finir !
Tu en as besoin de suite ? 

Si jamais tu y arrives de ton côté, n'hésite pas à me dire.

**Comment by ThomasRitaine** [comment]
Salut @n3rada !

Pas de problème prend ton temps ;)
Je suis nouveau sur LaTeX, donc je ne comprends pas grand chose 😅
Je l'utiliserai le semestre prochain pour mon rapport ST09

**Comment by n3rada** [comment]
Salut @ThomasRitaine ! 🤝 

Merci de m'avoir montré ce bug.
Je t'avoue n'avoir dev qu'uniquement sur VsCode.

Je me suis créé un compte Overleaf dans la foulée pour comprendre d'où venait le souci !

Finalement, je l'ai trouvé. 

Overleaf semble ne pas aimer l'utilisation d' "include" : 
![image](https://user-images.githubusercontent.com/72791564/121497726-05aacd80-c9dc-11eb-800e-a7fe1773ab81.png)

Du coup je l'ai changé avec un "import" et tout semble fonctionner !
![image](https://user-images.githubusercontent.com/72791564/121497801-18250700-c9dc-11eb-916c-2bce59cd6e0e.png)

Du coup, je vais pull la modification et tu vas pouvoir l'utiliser 💯

**Comment by ThomasRitaine** [comment]
Salut @n3rada !

Pas de problème prend ton temps ;)
Je suis nouveau sur LaTeX, donc je ne comprends pas grand chose 😅
Je l'utiliserai le semestre prochain pour mon rapport ST09

C'est super si tu arrives à trouver le problème ;)
