### ISSUE TITLE
Problèmes à la compilation avec make

### ISSUE THREAD

**Issue by axelcalixte** [n3rada/ScribUTT#6]
Bonjour !

Tout d'abord, un grand merci pour ce projet que j'utilise pour mon rapport de ST09 :)
Jusqu'ici j'utilisais ScribUTT sur Overleaf après l'avoir importé et la compilation se déroulait bien.

J'ai exporté mon projet et les changements sur ma machine linux en local et j'ai installé le gros metapaquet latex qui s'appelle `texlive-latex` sur openSUSE.

Malheureusement j'ai des problèmes lors du make et j'ai un bon gros rapportUTT.log de 336 lignes à examiner et je me disais que vous sauriez peut-être mieux l'appréhender.
-> [rapportUTT.log](https://cloud.disroot.org/s/ttn9ZCa55kBR4jn)

Ce serait vraiment super si vous pourriez jeter un coup d'oeil !

Sinon vous pouvez fermer l'issue sans soucis :)

Axel

**Comment by axelcalixte** [comment]
Bon c'était juste qu'il me fallait encore 5-10 dépendances pour le latex...

**Comment by n3rada** [comment]
Salut Axel,

Merci pour ton message !
Oui, souvent pour ce genre de bugs, je ne peux pas y faire grand chose, ça dépend tellement des conditions initiales de tout un chacun...

Si un jour tu trouves un problème et que tu arrives à le corriger, n'hésites pas à me le signaler ou à faire une pull request !

Bien à toi,

**Comment by Zalk0** [comment]
Salut,

Si c'était possible d'avoir une liste des dépendances sans chercher tous les usepackage ce serait cool je pense. 
Genre faire un petit paragraphe dans le Readme 🤔 
(Je pourrais éventuellement le faire pendant le mois de février si j'y pense)
Bonne journée

**Comment by n3rada** [comment]
J'avais pensé à faire un `requirement.txt` comme en python. Sauf qu'ici, ça dépend trop des versions utilisées, de ton OS source etc.

Vu que je suis sous Arch Linux, j'ai pas les mêmes soucis que ceux sous un autre OS.
Il faudrait que tout le monde prenne le temps de noter son processus d'installation et comme ça on pourrait le regrouper !

Qu'en pensez-vous ?

**Comment by axelcalixte** [comment]
Je pourrais m'occuper des dépendances en deb et rpm parce que j'ai de l'expérience avec Debian et openSUSE (qui j'espère utilise les mêmes noms de paquets pour ses rpm que ceux de Fedora).
Maintenant que j'ai compris le principe pour pouvoir compiler le projet.

Je pense que ce serait bien utile.

Peitte question à part, la comm' de l'utt valide toujours l'utilisation de ton projet @n3rada ?

**Comment by n3rada** [comment]
Bien sûr !
Le projet apparaît même sur la page **Les ressources graphiques de l'UTT** sur moodle !

J'aimerais beaucoup que tu apportes ta pierre à l'édifice avec ton idée @axelcalixte .
Plus on sera à le faire vivre et plus on pourra rédiger nos rapports sans avoir à passer 5 jours sur la mise en forme.

Notre but est de produire du contenu pas de la forme en tant qu'ingénieur normalement.

**Comment by axelcalixte** [comment]
OUUUUI après presque une heure de chiant

Et oui ne pas oublier de `pip install Pygments`, je ne l'ai pas précisé

```markdown
# openSUSE 

## zypper option : `--no-recommends` (for minimum dependencies installed)
## `sudo ln -sf /usr/bin/python3.8 /usr/bin/python` (was required for me with Pygments)
## `texlive-texcount` for a function of VimTex vim latex plugin
## `texlive-chktex` for diagnostics of latex file with neovim and null-ls plugin

`texlive-latexmk` (which brings the texlive-latex metapackage) 

`texlive-emptypage texlive-setspace texlive-soul texlive-datetime2 texlive-bookmark texlive-microtype texlive-floatrow texlive-titling texlive-blindtext texlive-adjustbox texlive-subfiles texlive-animate texlive-ulem texlive-multirow texlive-mathtools texlive-todonotes texlive-enumitem texlive-psnfss texlive-textpos texlive-frankenstein texlive-quoting texlive-epigraph texlive-minted texlive-tcolorbox texlive-csquotes texlive-mdframed texlive-braket texlive-titlesec texlive-appendix texlive-tocloft texlive-etoc texlive-shorttoc texlive-fancyhdr texlive-bigfoot texlive-biber-bin texlive-babel-french texlive-babel-english texlive-hyperxmp texlive-censor`
````

edit : J'ai pu rajouté 3 paquets qui manquaient à la suite de mes commentaires dans rUTT.cls
